### ISSUE TITLE
Way to name tracks?

### ISSUE THREAD

**Issue by ffolkes** [4gra/pclk-mn10#2]
Thanks for your great work on this, I was able to get it running with my MXD-D40, PCLK-MN10, an Mac. Do you know how to input a track title? Is that possible? The XP client allows it, but I don't know what command it is using to do it. Thanks for any help!

**Comment by 4gra** [comment]
Thanks so much for reporting back, great to add another model to the fold. Yes, it's entirely possible to title tracks using this mechanism, but I've never gotten around to adding it, and titles are probably one of the trickier things to compose.

You can *get* titles using something like: `(09 00 60) B0 48 00 01 <track no> 00 <chunk>"` (where chunks and track numbers start at `01`), and you will be able to set them using something like `B0 98 00 01 <track number> 00  <chunk> <data>` but the devil's in the detail of `<data>` of course.  Formatting ASCII into the title should be easy enough, but there are other little tricks in the encoding.

I'll dig out better records if that's not enough of a start for you -- I'd appreciate any research or achievements you make.

**Comment by ffolkes** [comment]
I was able to get a USB sniffer running on the XP VM I use for M-Crew, and I titled a disc "testing" and stopped capturing. I have no idea how to figure out how you knew what hex does what, so I just searched for "98 00 01" and this came up. Note: this was a disc title operation, not a track title. The string "testing" was referenced several times, but only once from the PC to the deck.

Here is that packet:

0000   1b 00 48 ee 46 82 ff ff ff ff 00 00 00 00 09 00
0010   00 02 00 04 00 01 03 1a 00 00 00 19 00 60 b0 98
0020   00 01 00 00 01 74 65 73 74 69 6e 67 00 00 00 00
0030   00 00 00 00 00

"testing" is "74 65 73 74 69 6e 67" in ASCII, which starts in the middle of line 0020.

Then another packet comes from the PC after that one:

0000   1b 00 48 ee 46 82 ff ff ff ff 00 00 00 00 09 00
0010   01 02 00 04 00 01 03 00 00 00 00

I don't have enough knowledge of Python (actually, any, at all) to figure out what your script is doing, but I tried adding to your JSON a test command:

`"MDdisctitletesting":"b0 98 00 01 00 00 01 74 65 73 74 69 6e 67 00 00 00 00 00 00 00 00 00",`

But it doesn't work. My goal with all of this is not to name discs (I just thought that would be the easiest starting place), but to name tracks. I made a script that monitors VLC, and when the track changes, it sends the "MDrec" command to the deck to mark the new track. I'm hoping to eventually be able to also send a "MDnametrack" command with the current song title to make my life complete.

Any input is very much appreciated!

**Comment by ffolkes** [comment]
It seems to be working now! Turns out sometimes the deck gets stuck. I'm not sure what causes it yet, perhaps the switching between VMware/XP and OS X, or maybe something M-Crew is doing. I can tell, because "off" doesn't do anything. Once I manually turn it off, "on" and "off" work again. Then when I tried "b0 98 00 01 00 00 01 74 65 73 74 69 6e 67 00 00 00 00 00 00 00 00 00" the name changed! I will try more, and see how it works.

When you say "chunks" what do you mean?

**Comment by 4gra** [comment]
M-Crew definitely sends (and reads) more than is required.  Also note there are a display updates taking place according to some protocol (which might differ a little depending on model) - one mini-project I keep meaning to start is to keep track of the latest display state as it is updated.

If your device doesn't have the ability to power off remotely, it might just be that you're powering off the PCLK-MN10; it's easy to get that into a state where it doesn't wake up until a re-plug. But if you discover anything unique to the MXD-D40 we can record it here.

As to "why `B0`?" - that's the global "address" Sony give to MiniDisc devices / modules in the command space - well actually '`B`' is the minidisc value; '`9`' is the CD module, etc.  Messages to the MD module use `B0`; replies use `B8`. Take a look at https://github.com/4gra/pclk-mn10/blob/master/commands.json where you should be able to see some patterns.  I discuss this in the wiki but never really formalised it, and I should have done.

**Comment by 4gra** [comment]
By the way these are all great additions and I'd be happy to integrate the new titling commands. I probably don't have the ability to add commands with ASCII parameters right now, so I'll add that functionality to the python.  Shouldn't take too long but in the meanwhile your research continues to be appreciated - hopefully we'll get something useful together.

**Comment by 4gra** [comment]
Converting this to a discussion - I'll definitely add track and disc titling commands based on this work.
